// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, TargetPlatform, kIsWeb;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macOS - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for Windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for Linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.fuchsia:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for Fuchsia - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: "AIzaSyD84NVbXkkzNrDpvXTuUxArBTcXrtpNBVE",
//     authDomain: "diabestant.firebaseapp.com",
//     projectId: "diabestant",
//     storageBucket: "diabestant.appspot.com",
//     messagingSenderId: "25128005252",
//     appId: "1:25128005252:web:e71756c43f837d994e9cd1",
//     measurementId: "G-54YDLPD8Q6",
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'Your-key',
//     appId: '1:757941782079:ios:662f379e338c8748125a8a',
//     messagingSenderId: '757941782079',
//     projectId: 'fcm-flutter-demo-a8f8f',
//     storageBucket: 'fcm-flutter-demo-a8f8f.appspot.com',
//     iosClientId:
//         '757941782079-mtmoukdf91egsh8tbjrfgj577pl25jam.apps.googleusercontent.com',
//     iosBundleId: 'com.id.pushnotifications',
//   );

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: "AIzaSyB-_4-FNjDLzJFnzY4dGCsX9s2oep6XlZ0",
//     authDomain: "diabestant.firebaseapp.com",
//     projectId: "diabestant",
//     storageBucket: "diabestant.appspot.com",
//     messagingSenderId: "25128005252",
//     appId: "1:25128005252:web:e71756c43f837d994e9cd1",
//     measurementId: "G-54YDLPD8Q6",
//   );
// }
